version: '3.11'

services:
  flask:
    # build: ./flaskr
    image: twilightwei/senao-flask:latest
    container_name: flask
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./flaskr/:/usr/src/app/
    expose:
      - 5000
    environment:
      - FLASK_APP=app/__init__.py
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask

# docker-compose down -v
# docker-compose -f docker-compose.yml up -d --build
# docker-compose exec template_flask bash
